services:
  backend:
    image: dropfile-backend
    container_name: dropfile-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./usr/src/app/uploads:/usr/src/app/uploads

    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: dropfile-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
